# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/work1/Works/CNN-Core-Wrapper/cnn_core_wrapper/cnn_core_wrapper.srcs/sources_1/ip/cnn_core_0/cnn_core_0.xci
# IP: The module: 'cnn_core_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/work1/Works/CNN-Core-Wrapper/cnn_core_wrapper/cnn_core_wrapper.gen/sources_1/ip/cnn_core_0/constraints/cnn_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_core_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/work1/Works/CNN-Core-Wrapper/cnn_core_wrapper/cnn_core_wrapper.srcs/sources_1/ip/cnn_core_0/cnn_core_0.xci
# IP: The module: 'cnn_core_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/work1/Works/CNN-Core-Wrapper/cnn_core_wrapper/cnn_core_wrapper.gen/sources_1/ip/cnn_core_0/constraints/cnn_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnn_core_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
