// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_core_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer4_out_dout,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer4_out_empty_n,
        layer4_out_read,
        layer5_out_din,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap,
        layer5_out_full_n,
        layer5_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [118:0] layer4_out_dout;
input  [9:0] layer4_out_num_data_valid;
input  [9:0] layer4_out_fifo_cap;
input   layer4_out_empty_n;
output   layer4_out_read;
output  [111:0] layer5_out_din;
input  [9:0] layer5_out_num_data_valid;
input  [9:0] layer5_out_fifo_cap;
input   layer5_out_full_n;
output   layer5_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer4_out_read;
reg layer5_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_111_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer4_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer5_out_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln51_fu_192_p2;
reg   [0:0] icmp_ln51_reg_426;
wire   [13:0] trunc_ln52_fu_198_p1;
reg   [13:0] trunc_ln52_reg_431;
wire   [0:0] icmp_ln51_1_fu_202_p2;
reg   [0:0] icmp_ln51_1_reg_436;
reg   [13:0] tmp_1_reg_441;
wire   [0:0] icmp_ln51_2_fu_218_p2;
reg   [0:0] icmp_ln51_2_reg_446;
reg   [13:0] tmp_2_reg_451;
wire   [0:0] icmp_ln51_3_fu_234_p2;
reg   [0:0] icmp_ln51_3_reg_456;
reg   [13:0] tmp_3_reg_461;
wire   [0:0] icmp_ln51_4_fu_250_p2;
reg   [0:0] icmp_ln51_4_reg_466;
reg   [13:0] tmp_4_reg_471;
wire   [0:0] icmp_ln51_5_fu_266_p2;
reg   [0:0] icmp_ln51_5_reg_476;
reg   [13:0] tmp_5_reg_481;
wire   [0:0] icmp_ln51_6_fu_282_p2;
reg   [0:0] icmp_ln51_6_reg_486;
reg   [13:0] tmp_6_reg_491;
reg   [8:0] i_fu_86;
wire   [8:0] i_10_fu_117_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_i_9;
reg    ap_block_pp0_stage0_01001;
wire   [16:0] trunc_ln44_fu_128_p1;
wire   [16:0] trunc_ln44_1_fu_132_p4;
wire   [16:0] trunc_ln44_2_fu_142_p4;
wire   [16:0] trunc_ln44_3_fu_152_p4;
wire   [16:0] trunc_ln44_4_fu_162_p4;
wire   [16:0] trunc_ln44_5_fu_172_p4;
wire   [16:0] trunc_ln44_6_fu_182_p4;
wire   [15:0] out_data_fu_298_p3;
wire   [15:0] out_data_93_fu_312_p3;
wire   [15:0] out_data_95_fu_326_p3;
wire   [15:0] out_data_97_fu_340_p3;
wire   [15:0] shl_ln_fu_354_p3;
wire   [15:0] shl_ln52_1_fu_368_p3;
wire   [15:0] shl_ln52_2_fu_382_p3;
wire   [15:0] select_ln51_2_fu_389_p3;
wire   [15:0] select_ln51_1_fu_375_p3;
wire   [15:0] select_ln51_fu_361_p3;
wire   [15:0] out_data_98_fu_347_p3;
wire   [15:0] out_data_96_fu_333_p3;
wire   [15:0] out_data_94_fu_319_p3;
wire   [15:0] out_data_92_fu_305_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_141;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_fu_86 = 9'd0;
end

cnn_core_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_141)) begin
        if ((icmp_ln41_fu_111_p2 == 1'd0)) begin
            i_fu_86 <= i_10_fu_117_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_86 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln51_1_reg_436 <= icmp_ln51_1_fu_202_p2;
        icmp_ln51_2_reg_446 <= icmp_ln51_2_fu_218_p2;
        icmp_ln51_3_reg_456 <= icmp_ln51_3_fu_234_p2;
        icmp_ln51_4_reg_466 <= icmp_ln51_4_fu_250_p2;
        icmp_ln51_5_reg_476 <= icmp_ln51_5_fu_266_p2;
        icmp_ln51_6_reg_486 <= icmp_ln51_6_fu_282_p2;
        icmp_ln51_reg_426 <= icmp_ln51_fu_192_p2;
        tmp_1_reg_441 <= {{layer4_out_dout[30:17]}};
        tmp_2_reg_451 <= {{layer4_out_dout[47:34]}};
        tmp_3_reg_461 <= {{layer4_out_dout[64:51]}};
        tmp_4_reg_471 <= {{layer4_out_dout[81:68]}};
        tmp_5_reg_481 <= {{layer4_out_dout[98:85]}};
        tmp_6_reg_491 <= {{layer4_out_dout[115:102]}};
        trunc_ln52_reg_431 <= trunc_ln52_fu_198_p1;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_111_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_9 = 9'd0;
    end else begin
        ap_sig_allocacmp_i_9 = i_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer4_out_blk_n = layer4_out_empty_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer4_out_read = 1'b1;
    end else begin
        layer4_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer5_out_blk_n = layer5_out_full_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer5_out_write = 1'b1;
    end else begin
        layer5_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer4_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (layer5_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_141 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_10_fu_117_p2 = (ap_sig_allocacmp_i_9 + 9'd1);

assign icmp_ln41_fu_111_p2 = ((ap_sig_allocacmp_i_9 == 9'd336) ? 1'b1 : 1'b0);

assign icmp_ln51_1_fu_202_p2 = (($signed(trunc_ln44_1_fu_132_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_2_fu_218_p2 = (($signed(trunc_ln44_2_fu_142_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_3_fu_234_p2 = (($signed(trunc_ln44_3_fu_152_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_4_fu_250_p2 = (($signed(trunc_ln44_4_fu_162_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_5_fu_266_p2 = (($signed(trunc_ln44_5_fu_172_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_6_fu_282_p2 = (($signed(trunc_ln44_6_fu_182_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_192_p2 = (($signed(trunc_ln44_fu_128_p1) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign layer5_out_din = {{{{{{{select_ln51_2_fu_389_p3}, {select_ln51_1_fu_375_p3}}, {select_ln51_fu_361_p3}}, {out_data_98_fu_347_p3}}, {out_data_96_fu_333_p3}}, {out_data_94_fu_319_p3}}, {out_data_92_fu_305_p3}};

assign out_data_92_fu_305_p3 = ((icmp_ln51_reg_426[0:0] == 1'b1) ? out_data_fu_298_p3 : 16'd0);

assign out_data_93_fu_312_p3 = {{tmp_1_reg_441}, {2'd0}};

assign out_data_94_fu_319_p3 = ((icmp_ln51_1_reg_436[0:0] == 1'b1) ? out_data_93_fu_312_p3 : 16'd0);

assign out_data_95_fu_326_p3 = {{tmp_2_reg_451}, {2'd0}};

assign out_data_96_fu_333_p3 = ((icmp_ln51_2_reg_446[0:0] == 1'b1) ? out_data_95_fu_326_p3 : 16'd0);

assign out_data_97_fu_340_p3 = {{tmp_3_reg_461}, {2'd0}};

assign out_data_98_fu_347_p3 = ((icmp_ln51_3_reg_456[0:0] == 1'b1) ? out_data_97_fu_340_p3 : 16'd0);

assign out_data_fu_298_p3 = {{trunc_ln52_reg_431}, {2'd0}};

assign select_ln51_1_fu_375_p3 = ((icmp_ln51_5_reg_476[0:0] == 1'b1) ? shl_ln52_1_fu_368_p3 : 16'd0);

assign select_ln51_2_fu_389_p3 = ((icmp_ln51_6_reg_486[0:0] == 1'b1) ? shl_ln52_2_fu_382_p3 : 16'd0);

assign select_ln51_fu_361_p3 = ((icmp_ln51_4_reg_466[0:0] == 1'b1) ? shl_ln_fu_354_p3 : 16'd0);

assign shl_ln52_1_fu_368_p3 = {{tmp_5_reg_481}, {2'd0}};

assign shl_ln52_2_fu_382_p3 = {{tmp_6_reg_491}, {2'd0}};

assign shl_ln_fu_354_p3 = {{tmp_4_reg_471}, {2'd0}};

assign start_out = real_start;

assign trunc_ln44_1_fu_132_p4 = {{layer4_out_dout[33:17]}};

assign trunc_ln44_2_fu_142_p4 = {{layer4_out_dout[50:34]}};

assign trunc_ln44_3_fu_152_p4 = {{layer4_out_dout[67:51]}};

assign trunc_ln44_4_fu_162_p4 = {{layer4_out_dout[84:68]}};

assign trunc_ln44_5_fu_172_p4 = {{layer4_out_dout[101:85]}};

assign trunc_ln44_6_fu_182_p4 = {{layer4_out_dout[118:102]}};

assign trunc_ln44_fu_128_p1 = layer4_out_dout[16:0];

assign trunc_ln52_fu_198_p1 = layer4_out_dout[13:0];

endmodule //cnn_core_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_s
