# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/work1/Works/CNN-Core-Wrapper/cnn_core_wrapper/cnn_core_wrapper.runs/synth_1/WRAPPER_TOP.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku5p-ffva676-3-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/work1/Works/CNN-Core-Wrapper/cnn_core_wrapper/cnn_core_wrapper.cache/wt [current_project]
set_property parent.project_path /home/work1/Works/CNN-Core-Wrapper/cnn_core_wrapper/cnn_core_wrapper.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/work1/Works/CNN-Core-Wrapper/cnn_core_wrapper/cnn_core_wrapper.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property verilog_define {TARGET_FPGA TARGET_SYNTHESIS TARGET_VIVADO TARGET_XILINX} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_dense_wide_stream_array_array_ap_fixed_1u_config7_Pipeline_DenseWideMain.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_dense_wide_stream_array_array_ap_fixed_9_5_5_3_0_1u_config7_s.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_fifo_w252_d4_S.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_fifo_w448_d4_S.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_first_conv_4lane_temporal_wide_cl_array_array_ap_fixed_28u_config3_s.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_flow_control_loop_pipe.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_flow_control_loop_pipe_sequential_init.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_28u_config5_s.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_mul_12s_5ns_15_1_1.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_mul_16s_6s_20_1_1.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_regslice_both.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_relu_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_28u_relu_config4_s.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_sparsemux_11_3_12_1_1.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_sparsemux_2353_11_6_1_1.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_sparsemux_9_2_16_1_1.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_start_for_dense_wide_stream_array_array_ap_fixed_9_5_5_3_0_1u_config7_U0.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_start_for_maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_28u_config5_U0.v
  /home/work1/Works/CNN-Core-Generator/hls_streaming/cnn_core_streaming_prj/solution1/impl/verilog/cnn_core_start_for_relu_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_28u_relu_config4_U0.v
  /home/work1/Works/CNN-Core-Wrapper/hw/rtl/cnn_core_wrapper_top.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/01_clocks.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/01_clocks.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/02_io_delays.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/02_io_delays.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/03_clock_groups.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/03_clock_groups.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/04_uncertainty.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/04_uncertainty.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/05_multicycle_falsepaths.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/05_multicycle_falsepaths.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/10_io_standards.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/10_io_standards.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/20_pins.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/20_pins.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/21_diff_pairs.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/21_diff_pairs.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/22_interface_adc.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/22_interface_adc.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/23_interface_spi.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/23_interface_spi.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/24_interface_axi.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/24_interface_axi.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/30_timing_extras.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/30_timing_extras.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/40_debug_ila.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/40_debug_ila.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/50_power_thermal.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/50_power_thermal.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/99_local_override.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/99_local_override.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/01_clocks.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/01_clocks.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/02_io_delays.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/02_io_delays.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/03_clock_groups.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/03_clock_groups.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/04_uncertainty.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/04_uncertainty.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/05_multicycle_falsepaths.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/05_multicycle_falsepaths.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/10_io_standards.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/10_io_standards.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/20_pins.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/20_pins.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/21_diff_pairs.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/21_diff_pairs.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/22_interface_adc.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/22_interface_adc.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/23_interface_spi.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/23_interface_spi.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/24_interface_axi.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/24_interface_axi.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/30_timing_extras.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/30_timing_extras.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/40_debug_ila.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/40_debug_ila.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/50_power_thermal.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/50_power_thermal.xdc]

read_xdc /home/work1/Works/CNN-Core-Wrapper/hw/xdc/99_local_override.xdc
set_property used_in_implementation false [get_files /home/work1/Works/CNN-Core-Wrapper/hw/xdc/99_local_override.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/work1/Works/CNN-Core-Wrapper/cnn_core_wrapper/cnn_core_wrapper.srcs/utils_1/imports/synth_1/WRAPPER_TOP.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top WRAPPER_TOP -part xcku5p-ffva676-3-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef WRAPPER_TOP.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file WRAPPER_TOP_utilization_synth.rpt -pb WRAPPER_TOP_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
