// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_core_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer6_out_din,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap,
        layer6_out_full_n,
        layer6_out_write,
        layer5_out_dout,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap,
        layer5_out_empty_n,
        layer5_out_read,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [111:0] layer6_out_din;
input  [8:0] layer6_out_num_data_valid;
input  [8:0] layer6_out_fifo_cap;
input   layer6_out_full_n;
output   layer6_out_write;
input  [111:0] layer5_out_dout;
input  [9:0] layer5_out_num_data_valid;
input  [9:0] layer5_out_fifo_cap;
input   layer5_out_empty_n;
output   layer5_out_read;
output   start_out;
output   start_write;

reg ap_idle;
reg layer6_out_write;
reg layer5_out_read;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] and_ln55_1_reg_612;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln109_fu_172_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln109_reg_608;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_pp0_stage1_subdone;
reg   [15:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9;
reg   [15:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2;
reg   [15:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8;
reg   [15:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1;
reg   [15:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7;
reg   [15:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel;
reg   [15:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3;
reg   [15:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2;
reg   [15:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1;
reg   [15:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3;
reg   [15:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap;
reg   [31:0] pX;
reg   [31:0] sX;
reg   [31:0] pY;
reg    layer5_out_blk_n;
wire    ap_block_pp0_stage1;
reg    layer6_out_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] and_ln55_1_fu_228_p2;
reg    ap_enable_reg_pp0_iter0_reg;
wire    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_ap_ready;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read1;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read2;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read3;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read4;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read5;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read6;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9;
wire    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8;
wire    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_ap_vld;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7;
wire    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_ap_vld;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6;
wire    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_ap_vld;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5;
wire    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_ap_vld;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4;
wire    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o;
wire    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_ap_vld;
wire   [15:0] call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3;
wire    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_ap_vld;
reg    ap_block_pp0_stage1_11001;
wire   [31:0] add_ln76_fu_234_p2;
wire   [0:0] icmp_ln76_fu_240_p2;
wire   [31:0] add_ln91_fu_260_p2;
wire   [31:0] select_ln80_fu_296_p3;
reg   [8:0] indvar_flatten_fu_108;
wire   [8:0] add_ln109_fu_178_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] tmp_fu_198_p3;
wire   [0:0] icmp_ln55_1_fu_216_p2;
wire   [0:0] xor_ln55_fu_206_p2;
wire   [0:0] and_ln55_fu_222_p2;
wire   [0:0] icmp_ln55_fu_188_p2;
wire   [31:0] select_ln91_fu_252_p3;
wire   [31:0] add_ln80_fu_284_p2;
wire   [0:0] icmp_ln80_fu_290_p2;
wire   [0:0] icmp_ln66_fu_394_p2;
wire   [0:0] xor_ln66_fu_400_p2;
wire   [0:0] icmp_ln66_1_fu_422_p2;
wire   [0:0] xor_ln66_1_fu_428_p2;
wire   [0:0] icmp_ln66_2_fu_450_p2;
wire   [0:0] xor_ln66_2_fu_456_p2;
wire   [0:0] icmp_ln66_3_fu_478_p2;
wire   [0:0] xor_ln66_3_fu_484_p2;
wire   [0:0] icmp_ln66_4_fu_506_p2;
wire   [0:0] xor_ln66_4_fu_512_p2;
wire   [0:0] icmp_ln66_5_fu_534_p2;
wire   [0:0] xor_ln66_5_fu_540_p2;
wire   [0:0] icmp_ln66_6_fu_562_p2;
wire   [0:0] xor_ln66_6_fu_568_p2;
wire   [15:0] res_pack_6_fu_574_p3;
wire   [15:0] res_pack_5_fu_546_p3;
wire   [15:0] res_pack_4_fu_518_p3;
wire   [15:0] res_pack_3_fu_490_p3;
wire   [15:0] res_pack_2_fu_462_p3;
wire   [15:0] res_pack_1_fu_434_p3;
wire   [15:0] res_pack_fu_406_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_263;
reg    ap_condition_292;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 = 16'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2 = 16'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8 = 16'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 = 16'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 = 16'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel = 16'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3 = 16'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2 = 16'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1 = 16'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 = 16'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap = 16'd0;
#0 pX = 32'd0;
#0 sX = 32'd0;
#0 pY = 32'd0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 indvar_flatten_fu_108 = 9'd0;
end

cnn_core_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125(
    .ap_ready(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_ap_ready),
    .p_read(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read),
    .p_read1(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read1),
    .p_read2(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read2),
    .p_read3(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read3),
    .p_read4(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read4),
    .p_read5(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read5),
    .p_read6(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read6),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_i(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_i(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_i(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_i(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o),
    .p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_ap_vld),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3),
    .void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_ap_vld(call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_ap_vld)
);

cnn_core_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_263)) begin
        if ((icmp_ln109_fu_172_p2 == 1'd0)) begin
            indvar_flatten_fu_108 <= add_ln109_fu_178_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_108 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_292)) begin
        if ((icmp_ln76_fu_240_p2 == 1'd1)) begin
            pX <= 32'd0;
        end else if ((icmp_ln76_fu_240_p2 == 1'd0)) begin
            pX <= add_ln76_fu_234_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_292)) begin
        if ((icmp_ln76_fu_240_p2 == 1'd1)) begin
            sX <= 32'd0;
        end else if ((icmp_ln76_fu_240_p2 == 1'd0)) begin
            sX <= add_ln91_fu_260_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln55_1_reg_612 <= and_ln55_1_fu_228_p2;
        icmp_ln109_reg_608 <= icmp_ln109_fu_172_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_172_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln76_fu_240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pY <= select_ln80_fu_296_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_ap_vld == 1'b1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_ap_vld == 1'b1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_ap_vld == 1'b1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_ap_vld == 1'b1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld == 1'b1))) begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9;
    end
end

always @ (*) begin
    if (((icmp_ln109_fu_172_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_108;
    end
end

always @ (*) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer5_out_blk_n = layer5_out_empty_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln109_reg_608 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        layer5_out_read = 1'b1;
    end else begin
        layer5_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln55_1_reg_612) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_blk_n = layer6_out_full_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln55_1_reg_612) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_write = 1'b1;
    end else begin
        layer6_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_fu_178_p2 = (ap_sig_allocacmp_indvar_flatten_load + 9'd1);

assign add_ln76_fu_234_p2 = (pX + 32'd1);

assign add_ln80_fu_284_p2 = (pY + 32'd1);

assign add_ln91_fu_260_p2 = (sX + select_ln91_fu_252_p3);

assign and_ln55_1_fu_228_p2 = (icmp_ln55_fu_188_p2 & and_ln55_fu_222_p2);

assign and_ln55_fu_222_p2 = (xor_ln55_fu_206_p2 & icmp_ln55_1_fu_216_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((icmp_ln109_reg_608 == 1'd0) & (layer5_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((1'd1 == and_ln55_1_reg_612) & (layer6_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_263 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_292 = ((icmp_ln109_fu_172_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read = layer5_out_dout[15:0];

assign call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read1 = {{layer5_out_dout[31:16]}};

assign call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read2 = {{layer5_out_dout[47:32]}};

assign call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read3 = {{layer5_out_dout[63:48]}};

assign call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read4 = {{layer5_out_dout[79:64]}};

assign call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read5 = {{layer5_out_dout[95:80]}};

assign call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s_fu_125_p_read6 = {{layer5_out_dout[111:96]}};

assign icmp_ln109_fu_172_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 9'd336) ? 1'b1 : 1'b0);

assign icmp_ln55_1_fu_216_p2 = (($signed(pX) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_188_p2 = ((sX == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln66_1_fu_422_p2 = (($signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8) < $signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1)) ? 1'b1 : 1'b0);

assign icmp_ln66_2_fu_450_p2 = (($signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7) < $signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel)) ? 1'b1 : 1'b0);

assign icmp_ln66_3_fu_478_p2 = (($signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6) < $signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3)) ? 1'b1 : 1'b0);

assign icmp_ln66_4_fu_506_p2 = (($signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5) < $signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2)) ? 1'b1 : 1'b0);

assign icmp_ln66_5_fu_534_p2 = (($signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4) < $signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1)) ? 1'b1 : 1'b0);

assign icmp_ln66_6_fu_562_p2 = (($signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3) < $signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap)) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_394_p2 = (($signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9) < $signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2)) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_240_p2 = ((add_ln76_fu_234_p2 == 32'd84) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_290_p2 = ((add_ln80_fu_284_p2 == 32'd4) ? 1'b1 : 1'b0);

assign layer6_out_din = {{{{{{{res_pack_6_fu_574_p3}, {res_pack_5_fu_546_p3}}, {res_pack_4_fu_518_p3}}, {res_pack_3_fu_490_p3}}, {res_pack_2_fu_462_p3}}, {res_pack_1_fu_434_p3}}, {res_pack_fu_406_p3}};

assign res_pack_1_fu_434_p3 = ((xor_ln66_1_fu_428_p2[0:0] == 1'b1) ? void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8 : void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1);

assign res_pack_2_fu_462_p3 = ((xor_ln66_2_fu_456_p2[0:0] == 1'b1) ? void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 : void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel);

assign res_pack_3_fu_490_p3 = ((xor_ln66_3_fu_484_p2[0:0] == 1'b1) ? void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 : p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3);

assign res_pack_4_fu_518_p3 = ((xor_ln66_4_fu_512_p2[0:0] == 1'b1) ? void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 : p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2);

assign res_pack_5_fu_546_p3 = ((xor_ln66_5_fu_540_p2[0:0] == 1'b1) ? void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 : p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1);

assign res_pack_6_fu_574_p3 = ((xor_ln66_6_fu_568_p2[0:0] == 1'b1) ? void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 : p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap);

assign res_pack_fu_406_p3 = ((xor_ln66_fu_400_p2[0:0] == 1'b1) ? void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 : void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2);

assign select_ln80_fu_296_p3 = ((icmp_ln80_fu_290_p2[0:0] == 1'b1) ? 32'd0 : add_ln80_fu_284_p2);

assign select_ln91_fu_252_p3 = ((icmp_ln55_fu_188_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign start_out = real_start;

assign tmp_fu_198_p3 = pY[32'd31];

assign xor_ln55_fu_206_p2 = (tmp_fu_198_p3 ^ 1'd1);

assign xor_ln66_1_fu_428_p2 = (icmp_ln66_1_fu_422_p2 ^ 1'd1);

assign xor_ln66_2_fu_456_p2 = (icmp_ln66_2_fu_450_p2 ^ 1'd1);

assign xor_ln66_3_fu_484_p2 = (icmp_ln66_3_fu_478_p2 ^ 1'd1);

assign xor_ln66_4_fu_512_p2 = (icmp_ln66_4_fu_506_p2 ^ 1'd1);

assign xor_ln66_5_fu_540_p2 = (icmp_ln66_5_fu_534_p2 ^ 1'd1);

assign xor_ln66_6_fu_568_p2 = (icmp_ln66_6_fu_562_p2 ^ 1'd1);

assign xor_ln66_fu_400_p2 = (icmp_ln66_fu_394_p2 ^ 1'd1);

endmodule //cnn_core_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_s
