// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_core_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer6_out_dout,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap,
        layer6_out_empty_n,
        layer6_out_read,
        layer12_out_din,
        layer12_out_num_data_valid,
        layer12_out_fifo_cap,
        layer12_out_full_n,
        layer12_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [111:0] layer6_out_dout;
input  [8:0] layer6_out_num_data_valid;
input  [8:0] layer6_out_fifo_cap;
input   layer6_out_empty_n;
output   layer6_out_read;
output  [671:0] layer12_out_din;
input  [5:0] layer12_out_num_data_valid;
input  [5:0] layer12_out_fifo_cap;
input   layer12_out_full_n;
output   layer12_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer6_out_read;
reg layer12_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln269_reg_1388;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln278_reg_1522;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln269_fu_278_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer6_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer12_out_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] in_data_fu_302_p1;
reg   [15:0] in_data_reg_1392;
reg   [15:0] in_data_4_reg_1402;
reg   [15:0] in_data_5_reg_1412;
reg   [15:0] in_data_6_reg_1422;
reg   [15:0] out_data_49_reg_1432;
reg   [15:0] out_data_1_reg_1442;
reg   [15:0] out_data_2_reg_1452;
wire   [0:0] icmp_ln275_fu_366_p2;
reg   [0:0] icmp_ln275_reg_1462;
wire   [0:0] icmp_ln275_1_fu_372_p2;
reg   [0:0] icmp_ln275_1_reg_1474;
wire   [0:0] icmp_ln275_2_fu_378_p2;
reg   [0:0] icmp_ln275_2_reg_1486;
wire   [0:0] icmp_ln275_3_fu_384_p2;
reg   [0:0] icmp_ln275_3_reg_1498;
wire   [0:0] icmp_ln275_4_fu_390_p2;
reg   [0:0] icmp_ln275_4_reg_1510;
wire   [0:0] icmp_ln278_fu_396_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
reg   [31:0] pack_cnt_fu_76;
wire   [31:0] pack_cnt_2_fu_402_p2;
wire    ap_loop_init;
reg    ap_loop_init_pp0_iter1_reg;
reg   [31:0] ap_sig_allocacmp_pack_cnt_1;
reg   [7:0] i_fu_80;
wire   [7:0] i_4_fu_284_p2;
reg   [7:0] ap_sig_allocacmp_i_3;
reg   [15:0] out_data_fu_84;
wire   [15:0] out_data_91_fu_816_p3;
reg   [15:0] out_data_4_fu_88;
wire   [15:0] out_data_90_fu_810_p3;
reg   [15:0] out_data_5_fu_92;
wire   [15:0] out_data_89_fu_804_p3;
reg   [15:0] out_data_6_fu_96;
wire   [15:0] out_data_88_fu_798_p3;
reg   [15:0] out_data_7_fu_100;
wire   [15:0] out_data_87_fu_792_p3;
reg   [15:0] out_data_8_fu_104;
wire   [15:0] out_data_86_fu_786_p3;
reg   [15:0] out_data_9_fu_108;
wire   [15:0] out_data_85_fu_780_p3;
reg   [15:0] out_data_10_fu_112;
wire   [15:0] out_data_84_fu_774_p3;
reg   [15:0] out_data_11_fu_116;
wire   [15:0] out_data_83_fu_768_p3;
reg   [15:0] out_data_12_fu_120;
wire   [15:0] out_data_82_fu_762_p3;
reg   [15:0] out_data_13_fu_124;
wire   [15:0] out_data_81_fu_756_p3;
reg   [15:0] out_data_14_fu_128;
wire   [15:0] out_data_80_fu_750_p3;
reg   [15:0] out_data_15_fu_132;
wire   [15:0] out_data_79_fu_744_p3;
reg   [15:0] out_data_16_fu_136;
wire   [15:0] out_data_78_fu_738_p3;
reg   [15:0] out_data_17_fu_140;
wire   [15:0] out_data_77_fu_732_p3;
reg   [15:0] out_data_18_fu_144;
wire   [15:0] out_data_76_fu_726_p3;
reg   [15:0] out_data_19_fu_148;
wire   [15:0] out_data_75_fu_720_p3;
reg   [15:0] out_data_20_fu_152;
wire   [15:0] out_data_74_fu_714_p3;
reg   [15:0] out_data_21_fu_156;
wire   [15:0] out_data_73_fu_708_p3;
reg   [15:0] out_data_22_fu_160;
wire   [15:0] out_data_72_fu_702_p3;
reg   [15:0] out_data_23_fu_164;
wire   [15:0] out_data_71_fu_696_p3;
reg   [15:0] out_data_24_fu_168;
wire   [15:0] out_data_70_fu_690_p3;
reg   [15:0] out_data_25_fu_172;
wire   [15:0] out_data_69_fu_684_p3;
reg   [15:0] out_data_26_fu_176;
wire   [15:0] out_data_68_fu_678_p3;
reg   [15:0] out_data_27_fu_180;
wire   [15:0] out_data_67_fu_672_p3;
reg   [15:0] out_data_28_fu_184;
wire   [15:0] out_data_66_fu_666_p3;
reg   [15:0] out_data_29_fu_188;
wire   [15:0] out_data_65_fu_660_p3;
reg   [15:0] out_data_30_fu_192;
wire   [15:0] out_data_64_fu_654_p3;
reg   [15:0] out_data_31_fu_196;
wire   [15:0] out_data_63_fu_648_p3;
reg   [15:0] out_data_32_fu_200;
wire   [15:0] out_data_62_fu_642_p3;
reg   [15:0] out_data_33_fu_204;
wire   [15:0] out_data_61_fu_636_p3;
reg   [15:0] out_data_34_fu_208;
wire   [15:0] out_data_60_fu_630_p3;
reg   [15:0] out_data_35_fu_212;
wire   [15:0] out_data_59_fu_624_p3;
reg   [15:0] out_data_36_fu_216;
wire   [15:0] out_data_58_fu_618_p3;
reg   [15:0] out_data_37_fu_220;
wire   [15:0] out_data_57_fu_612_p3;
reg   [15:0] out_data_38_fu_224;
wire   [15:0] out_data_56_fu_605_p3;
reg   [15:0] out_data_39_fu_228;
wire   [15:0] out_data_55_fu_598_p3;
reg   [15:0] out_data_40_fu_232;
wire   [15:0] out_data_54_fu_591_p3;
reg   [15:0] out_data_41_fu_236;
wire   [15:0] out_data_53_fu_584_p3;
reg   [15:0] out_data_42_fu_240;
wire   [15:0] out_data_52_fu_577_p3;
reg   [15:0] out_data_43_fu_244;
wire   [15:0] out_data_51_fu_570_p3;
reg   [15:0] out_data_44_fu_248;
wire   [15:0] out_data_50_fu_563_p3;
reg    ap_block_pp0_stage0_01001;
wire   [5:0] trunc_ln268_fu_298_p1;
wire   [0:0] or_ln275_fu_548_p2;
wire   [0:0] or_ln275_2_fu_552_p2;
wire   [0:0] or_ln275_1_fu_544_p2;
wire   [0:0] or_ln275_3_fu_557_p2;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_298;
reg    ap_condition_279;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 pack_cnt_fu_76 = 32'd0;
#0 i_fu_80 = 8'd0;
#0 out_data_fu_84 = 16'd0;
#0 out_data_4_fu_88 = 16'd0;
#0 out_data_5_fu_92 = 16'd0;
#0 out_data_6_fu_96 = 16'd0;
#0 out_data_7_fu_100 = 16'd0;
#0 out_data_8_fu_104 = 16'd0;
#0 out_data_9_fu_108 = 16'd0;
#0 out_data_10_fu_112 = 16'd0;
#0 out_data_11_fu_116 = 16'd0;
#0 out_data_12_fu_120 = 16'd0;
#0 out_data_13_fu_124 = 16'd0;
#0 out_data_14_fu_128 = 16'd0;
#0 out_data_15_fu_132 = 16'd0;
#0 out_data_16_fu_136 = 16'd0;
#0 out_data_17_fu_140 = 16'd0;
#0 out_data_18_fu_144 = 16'd0;
#0 out_data_19_fu_148 = 16'd0;
#0 out_data_20_fu_152 = 16'd0;
#0 out_data_21_fu_156 = 16'd0;
#0 out_data_22_fu_160 = 16'd0;
#0 out_data_23_fu_164 = 16'd0;
#0 out_data_24_fu_168 = 16'd0;
#0 out_data_25_fu_172 = 16'd0;
#0 out_data_26_fu_176 = 16'd0;
#0 out_data_27_fu_180 = 16'd0;
#0 out_data_28_fu_184 = 16'd0;
#0 out_data_29_fu_188 = 16'd0;
#0 out_data_30_fu_192 = 16'd0;
#0 out_data_31_fu_196 = 16'd0;
#0 out_data_32_fu_200 = 16'd0;
#0 out_data_33_fu_204 = 16'd0;
#0 out_data_34_fu_208 = 16'd0;
#0 out_data_35_fu_212 = 16'd0;
#0 out_data_36_fu_216 = 16'd0;
#0 out_data_37_fu_220 = 16'd0;
#0 out_data_38_fu_224 = 16'd0;
#0 out_data_39_fu_228 = 16'd0;
#0 out_data_40_fu_232 = 16'd0;
#0 out_data_41_fu_236 = 16'd0;
#0 out_data_42_fu_240 = 16'd0;
#0 out_data_43_fu_244 = 16'd0;
#0 out_data_44_fu_248 = 16'd0;
end

cnn_core_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_298)) begin
        if ((icmp_ln269_fu_278_p2 == 1'd0)) begin
            i_fu_80 <= i_4_fu_284_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_80 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_279)) begin
        if (((icmp_ln269_reg_1388 == 1'd0) & (icmp_ln278_fu_396_p2 == 1'd1))) begin
            pack_cnt_fu_76 <= 32'd0;
        end else if (((icmp_ln269_reg_1388 == 1'd0) & (icmp_ln278_fu_396_p2 == 1'd0))) begin
            pack_cnt_fu_76 <= pack_cnt_2_fu_402_p2;
        end else if ((ap_loop_init_pp0_iter1_reg == 1'b1)) begin
            pack_cnt_fu_76 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        icmp_ln269_reg_1388 <= icmp_ln269_fu_278_p2;
        icmp_ln275_1_reg_1474 <= icmp_ln275_1_fu_372_p2;
        icmp_ln275_2_reg_1486 <= icmp_ln275_2_fu_378_p2;
        icmp_ln275_3_reg_1498 <= icmp_ln275_3_fu_384_p2;
        icmp_ln275_4_reg_1510 <= icmp_ln275_4_fu_390_p2;
        icmp_ln275_reg_1462 <= icmp_ln275_fu_366_p2;
        icmp_ln278_reg_1522 <= icmp_ln278_fu_396_p2;
        in_data_4_reg_1402 <= {{layer6_out_dout[31:16]}};
        in_data_5_reg_1412 <= {{layer6_out_dout[47:32]}};
        in_data_6_reg_1422 <= {{layer6_out_dout[63:48]}};
        in_data_reg_1392 <= in_data_fu_302_p1;
        out_data_1_reg_1442 <= {{layer6_out_dout[95:80]}};
        out_data_2_reg_1452 <= {{layer6_out_dout[111:96]}};
        out_data_49_reg_1432 <= {{layer6_out_dout[79:64]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_data_10_fu_112 <= out_data_84_fu_774_p3;
        out_data_11_fu_116 <= out_data_83_fu_768_p3;
        out_data_12_fu_120 <= out_data_82_fu_762_p3;
        out_data_13_fu_124 <= out_data_81_fu_756_p3;
        out_data_14_fu_128 <= out_data_80_fu_750_p3;
        out_data_15_fu_132 <= out_data_79_fu_744_p3;
        out_data_16_fu_136 <= out_data_78_fu_738_p3;
        out_data_17_fu_140 <= out_data_77_fu_732_p3;
        out_data_18_fu_144 <= out_data_76_fu_726_p3;
        out_data_19_fu_148 <= out_data_75_fu_720_p3;
        out_data_20_fu_152 <= out_data_74_fu_714_p3;
        out_data_21_fu_156 <= out_data_73_fu_708_p3;
        out_data_22_fu_160 <= out_data_72_fu_702_p3;
        out_data_23_fu_164 <= out_data_71_fu_696_p3;
        out_data_24_fu_168 <= out_data_70_fu_690_p3;
        out_data_25_fu_172 <= out_data_69_fu_684_p3;
        out_data_26_fu_176 <= out_data_68_fu_678_p3;
        out_data_27_fu_180 <= out_data_67_fu_672_p3;
        out_data_28_fu_184 <= out_data_66_fu_666_p3;
        out_data_29_fu_188 <= out_data_65_fu_660_p3;
        out_data_30_fu_192 <= out_data_64_fu_654_p3;
        out_data_31_fu_196 <= out_data_63_fu_648_p3;
        out_data_32_fu_200 <= out_data_62_fu_642_p3;
        out_data_33_fu_204 <= out_data_61_fu_636_p3;
        out_data_34_fu_208 <= out_data_60_fu_630_p3;
        out_data_35_fu_212 <= out_data_59_fu_624_p3;
        out_data_36_fu_216 <= out_data_58_fu_618_p3;
        out_data_37_fu_220 <= out_data_57_fu_612_p3;
        out_data_38_fu_224 <= out_data_56_fu_605_p3;
        out_data_39_fu_228 <= out_data_55_fu_598_p3;
        out_data_40_fu_232 <= out_data_54_fu_591_p3;
        out_data_41_fu_236 <= out_data_53_fu_584_p3;
        out_data_42_fu_240 <= out_data_52_fu_577_p3;
        out_data_43_fu_244 <= out_data_51_fu_570_p3;
        out_data_44_fu_248 <= out_data_50_fu_563_p3;
        out_data_4_fu_88 <= out_data_90_fu_810_p3;
        out_data_5_fu_92 <= out_data_89_fu_804_p3;
        out_data_6_fu_96 <= out_data_88_fu_798_p3;
        out_data_7_fu_100 <= out_data_87_fu_792_p3;
        out_data_8_fu_104 <= out_data_86_fu_786_p3;
        out_data_9_fu_108 <= out_data_85_fu_780_p3;
        out_data_fu_84 <= out_data_91_fu_816_p3;
    end
end

always @ (*) begin
    if (((icmp_ln269_fu_278_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln269_reg_1388 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_3 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_loop_init_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_pack_cnt_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_pack_cnt_1 = pack_cnt_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln278_reg_1522 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer12_out_blk_n = layer12_out_full_n;
    end else begin
        layer12_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln278_reg_1522 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer12_out_write = 1'b1;
    end else begin
        layer12_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln269_reg_1388 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_blk_n = layer6_out_empty_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln269_reg_1388 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_read = 1'b1;
    end else begin
        layer6_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln269_reg_1388 == 1'd0) & (layer6_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((icmp_ln278_reg_1522 == 1'd1) & (layer12_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_279 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_298 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_4_fu_284_p2 = (ap_sig_allocacmp_i_3 + 8'd1);

assign icmp_ln269_fu_278_p2 = ((ap_sig_allocacmp_i_3 == 8'd168) ? 1'b1 : 1'b0);

assign icmp_ln275_1_fu_372_p2 = ((trunc_ln268_fu_298_p1 == 6'd1) ? 1'b1 : 1'b0);

assign icmp_ln275_2_fu_378_p2 = ((trunc_ln268_fu_298_p1 == 6'd2) ? 1'b1 : 1'b0);

assign icmp_ln275_3_fu_384_p2 = ((trunc_ln268_fu_298_p1 == 6'd3) ? 1'b1 : 1'b0);

assign icmp_ln275_4_fu_390_p2 = ((trunc_ln268_fu_298_p1 == 6'd4) ? 1'b1 : 1'b0);

assign icmp_ln275_fu_366_p2 = ((trunc_ln268_fu_298_p1 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln278_fu_396_p2 = ((ap_sig_allocacmp_pack_cnt_1 == 32'd5) ? 1'b1 : 1'b0);

assign in_data_fu_302_p1 = layer6_out_dout[15:0];

assign layer12_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{out_data_50_fu_563_p3}, {out_data_51_fu_570_p3}}, {out_data_52_fu_577_p3}}, {out_data_53_fu_584_p3}}, {out_data_54_fu_591_p3}}, {out_data_55_fu_598_p3}}, {out_data_56_fu_605_p3}}, {out_data_57_fu_612_p3}}, {out_data_58_fu_618_p3}}, {out_data_59_fu_624_p3}}, {out_data_60_fu_630_p3}}, {out_data_61_fu_636_p3}}, {out_data_62_fu_642_p3}}, {out_data_63_fu_648_p3}}, {out_data_64_fu_654_p3}}, {out_data_65_fu_660_p3}}, {out_data_66_fu_666_p3}}, {out_data_67_fu_672_p3}}, {out_data_68_fu_678_p3}}, {out_data_69_fu_684_p3}}, {out_data_70_fu_690_p3}}, {out_data_71_fu_696_p3}}, {out_data_72_fu_702_p3}}, {out_data_73_fu_708_p3}}, {out_data_74_fu_714_p3}}, {out_data_75_fu_720_p3}}, {out_data_76_fu_726_p3}}, {out_data_77_fu_732_p3}}, {out_data_78_fu_738_p3}}, {out_data_79_fu_744_p3}}, {out_data_80_fu_750_p3}}, {out_data_81_fu_756_p3}}, {out_data_82_fu_762_p3}}, {out_data_83_fu_768_p3}}, {out_data_84_fu_774_p3}}, {out_data_85_fu_780_p3}}, {out_data_86_fu_786_p3}}, {out_data_87_fu_792_p3}}, 
    {out_data_88_fu_798_p3}}, {out_data_89_fu_804_p3}}, {out_data_90_fu_810_p3}}, {out_data_91_fu_816_p3}};

assign or_ln275_1_fu_544_p2 = (icmp_ln275_reg_1462 | icmp_ln275_4_reg_1510);

assign or_ln275_2_fu_552_p2 = (or_ln275_fu_548_p2 | icmp_ln275_1_reg_1474);

assign or_ln275_3_fu_557_p2 = (or_ln275_2_fu_552_p2 | or_ln275_1_fu_544_p2);

assign or_ln275_fu_548_p2 = (icmp_ln275_3_reg_1498 | icmp_ln275_2_reg_1486);

assign out_data_50_fu_563_p3 = ((or_ln275_3_fu_557_p2[0:0] == 1'b1) ? out_data_44_fu_248 : out_data_2_reg_1452);

assign out_data_51_fu_570_p3 = ((or_ln275_3_fu_557_p2[0:0] == 1'b1) ? out_data_43_fu_244 : out_data_1_reg_1442);

assign out_data_52_fu_577_p3 = ((or_ln275_3_fu_557_p2[0:0] == 1'b1) ? out_data_42_fu_240 : out_data_49_reg_1432);

assign out_data_53_fu_584_p3 = ((or_ln275_3_fu_557_p2[0:0] == 1'b1) ? out_data_41_fu_236 : in_data_6_reg_1422);

assign out_data_54_fu_591_p3 = ((or_ln275_3_fu_557_p2[0:0] == 1'b1) ? out_data_40_fu_232 : in_data_5_reg_1412);

assign out_data_55_fu_598_p3 = ((or_ln275_3_fu_557_p2[0:0] == 1'b1) ? out_data_39_fu_228 : in_data_4_reg_1402);

assign out_data_56_fu_605_p3 = ((or_ln275_3_fu_557_p2[0:0] == 1'b1) ? out_data_38_fu_224 : in_data_reg_1392);

assign out_data_57_fu_612_p3 = ((icmp_ln275_4_reg_1510[0:0] == 1'b1) ? out_data_2_reg_1452 : out_data_37_fu_220);

assign out_data_58_fu_618_p3 = ((icmp_ln275_4_reg_1510[0:0] == 1'b1) ? out_data_1_reg_1442 : out_data_36_fu_216);

assign out_data_59_fu_624_p3 = ((icmp_ln275_4_reg_1510[0:0] == 1'b1) ? out_data_49_reg_1432 : out_data_35_fu_212);

assign out_data_60_fu_630_p3 = ((icmp_ln275_4_reg_1510[0:0] == 1'b1) ? in_data_6_reg_1422 : out_data_34_fu_208);

assign out_data_61_fu_636_p3 = ((icmp_ln275_4_reg_1510[0:0] == 1'b1) ? in_data_5_reg_1412 : out_data_33_fu_204);

assign out_data_62_fu_642_p3 = ((icmp_ln275_4_reg_1510[0:0] == 1'b1) ? in_data_4_reg_1402 : out_data_32_fu_200);

assign out_data_63_fu_648_p3 = ((icmp_ln275_4_reg_1510[0:0] == 1'b1) ? in_data_reg_1392 : out_data_31_fu_196);

assign out_data_64_fu_654_p3 = ((icmp_ln275_3_reg_1498[0:0] == 1'b1) ? out_data_2_reg_1452 : out_data_30_fu_192);

assign out_data_65_fu_660_p3 = ((icmp_ln275_3_reg_1498[0:0] == 1'b1) ? out_data_1_reg_1442 : out_data_29_fu_188);

assign out_data_66_fu_666_p3 = ((icmp_ln275_3_reg_1498[0:0] == 1'b1) ? out_data_49_reg_1432 : out_data_28_fu_184);

assign out_data_67_fu_672_p3 = ((icmp_ln275_3_reg_1498[0:0] == 1'b1) ? in_data_6_reg_1422 : out_data_27_fu_180);

assign out_data_68_fu_678_p3 = ((icmp_ln275_3_reg_1498[0:0] == 1'b1) ? in_data_5_reg_1412 : out_data_26_fu_176);

assign out_data_69_fu_684_p3 = ((icmp_ln275_3_reg_1498[0:0] == 1'b1) ? in_data_4_reg_1402 : out_data_25_fu_172);

assign out_data_70_fu_690_p3 = ((icmp_ln275_3_reg_1498[0:0] == 1'b1) ? in_data_reg_1392 : out_data_24_fu_168);

assign out_data_71_fu_696_p3 = ((icmp_ln275_2_reg_1486[0:0] == 1'b1) ? out_data_2_reg_1452 : out_data_23_fu_164);

assign out_data_72_fu_702_p3 = ((icmp_ln275_2_reg_1486[0:0] == 1'b1) ? out_data_1_reg_1442 : out_data_22_fu_160);

assign out_data_73_fu_708_p3 = ((icmp_ln275_2_reg_1486[0:0] == 1'b1) ? out_data_49_reg_1432 : out_data_21_fu_156);

assign out_data_74_fu_714_p3 = ((icmp_ln275_2_reg_1486[0:0] == 1'b1) ? in_data_6_reg_1422 : out_data_20_fu_152);

assign out_data_75_fu_720_p3 = ((icmp_ln275_2_reg_1486[0:0] == 1'b1) ? in_data_5_reg_1412 : out_data_19_fu_148);

assign out_data_76_fu_726_p3 = ((icmp_ln275_2_reg_1486[0:0] == 1'b1) ? in_data_4_reg_1402 : out_data_18_fu_144);

assign out_data_77_fu_732_p3 = ((icmp_ln275_2_reg_1486[0:0] == 1'b1) ? in_data_reg_1392 : out_data_17_fu_140);

assign out_data_78_fu_738_p3 = ((icmp_ln275_1_reg_1474[0:0] == 1'b1) ? out_data_2_reg_1452 : out_data_16_fu_136);

assign out_data_79_fu_744_p3 = ((icmp_ln275_1_reg_1474[0:0] == 1'b1) ? out_data_1_reg_1442 : out_data_15_fu_132);

assign out_data_80_fu_750_p3 = ((icmp_ln275_1_reg_1474[0:0] == 1'b1) ? out_data_49_reg_1432 : out_data_14_fu_128);

assign out_data_81_fu_756_p3 = ((icmp_ln275_1_reg_1474[0:0] == 1'b1) ? in_data_6_reg_1422 : out_data_13_fu_124);

assign out_data_82_fu_762_p3 = ((icmp_ln275_1_reg_1474[0:0] == 1'b1) ? in_data_5_reg_1412 : out_data_12_fu_120);

assign out_data_83_fu_768_p3 = ((icmp_ln275_1_reg_1474[0:0] == 1'b1) ? in_data_4_reg_1402 : out_data_11_fu_116);

assign out_data_84_fu_774_p3 = ((icmp_ln275_1_reg_1474[0:0] == 1'b1) ? in_data_reg_1392 : out_data_10_fu_112);

assign out_data_85_fu_780_p3 = ((icmp_ln275_reg_1462[0:0] == 1'b1) ? out_data_2_reg_1452 : out_data_9_fu_108);

assign out_data_86_fu_786_p3 = ((icmp_ln275_reg_1462[0:0] == 1'b1) ? out_data_1_reg_1442 : out_data_8_fu_104);

assign out_data_87_fu_792_p3 = ((icmp_ln275_reg_1462[0:0] == 1'b1) ? out_data_49_reg_1432 : out_data_7_fu_100);

assign out_data_88_fu_798_p3 = ((icmp_ln275_reg_1462[0:0] == 1'b1) ? in_data_6_reg_1422 : out_data_6_fu_96);

assign out_data_89_fu_804_p3 = ((icmp_ln275_reg_1462[0:0] == 1'b1) ? in_data_5_reg_1412 : out_data_5_fu_92);

assign out_data_90_fu_810_p3 = ((icmp_ln275_reg_1462[0:0] == 1'b1) ? in_data_4_reg_1402 : out_data_4_fu_88);

assign out_data_91_fu_816_p3 = ((icmp_ln275_reg_1462[0:0] == 1'b1) ? in_data_reg_1392 : out_data_fu_84);

assign pack_cnt_2_fu_402_p2 = (ap_sig_allocacmp_pack_cnt_1 + 32'd1);

assign start_out = real_start;

assign trunc_ln268_fu_298_p1 = ap_sig_allocacmp_pack_cnt_1[5:0];

endmodule //cnn_core_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_s
