// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cnn_core_cnn_core,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.650000,HLS_SYN_LAT=3218,HLS_SYN_TPT=3076,HLS_SYN_MEM=270,HLS_SYN_DSP=0,HLS_SYN_FF=64663,HLS_SYN_LUT=59402,HLS_VERSION=2023_2}" *)

module cnn_core (
        input_layer_TDATA,
        layer10_out_TDATA,
        ap_clk,
        ap_rst_n,
        input_layer_TVALID,
        input_layer_TREADY,
        ap_start,
        layer10_out_TVALID,
        layer10_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [63:0] input_layer_TDATA;
output  [31:0] layer10_out_TDATA;
input   ap_clk;
input   ap_rst_n;
input   input_layer_TVALID;
output   input_layer_TREADY;
input   ap_start;
output   layer10_out_TVALID;
input   layer10_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_ap_start;
wire    transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_ap_done;
wire    transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_ap_continue;
wire    transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_ap_idle;
wire    transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_ap_ready;
wire    transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_start_out;
wire    transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_start_write;
wire    transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_input_layer_TREADY;
wire   [3071:0] transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_layer2_out_din;
wire    transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_layer2_out_write;
wire    repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_ap_start;
wire    repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_ap_done;
wire    repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_ap_continue;
wire    repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_ap_idle;
wire    repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_ap_ready;
wire    repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_start_out;
wire    repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_start_write;
wire    repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_layer2_out_read;
wire   [11:0] repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_layer11_out_din;
wire    repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_layer11_out_write;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_ap_start;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_ap_done;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_ap_continue;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_ap_idle;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_ap_ready;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_layer11_out_read;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_start_out;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_start_write;
wire   [118:0] conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_layer4_out_din;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_layer4_out_write;
wire    relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_ap_start;
wire    relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_ap_done;
wire    relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_ap_continue;
wire    relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_ap_idle;
wire    relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_ap_ready;
wire    relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_layer4_out_read;
wire   [111:0] relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_layer5_out_din;
wire    relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_layer5_out_write;
wire    relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_start_out;
wire    relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_start_write;
wire    pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_ap_start;
wire    pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_ap_done;
wire    pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_ap_continue;
wire    pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_ap_idle;
wire    pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_ap_ready;
wire   [111:0] pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_layer6_out_din;
wire    pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_layer6_out_write;
wire    pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_layer5_out_read;
wire    pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_start_out;
wire    pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_start_write;
wire    repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_start;
wire    repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_done;
wire    repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_continue;
wire    repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_idle;
wire    repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_ready;
wire    repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer6_out_read;
wire   [671:0] repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer12_out_din;
wire    repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer12_out_write;
wire    repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_start_out;
wire    repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_start_write;
wire    repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_start;
wire    repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_done;
wire    repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_continue;
wire    repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_idle;
wire    repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_ready;
wire    repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer12_out_read;
wire   [671:0] repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer13_out_din;
wire    repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer13_out_write;
wire    repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_start_out;
wire    repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_start_write;
wire    dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_ap_start;
wire    dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_ap_done;
wire    dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_ap_continue;
wire    dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_ap_idle;
wire    dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_ap_ready;
wire    dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_layer13_out_read;
wire   [31:0] dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_layer10_out_TDATA;
wire    dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_layer10_out_TVALID;
wire    layer2_out_full_n;
wire   [3071:0] layer2_out_dout;
wire   [2:0] layer2_out_num_data_valid;
wire   [2:0] layer2_out_fifo_cap;
wire    layer2_out_empty_n;
wire    layer11_out_full_n;
wire   [11:0] layer11_out_dout;
wire   [10:0] layer11_out_num_data_valid;
wire   [10:0] layer11_out_fifo_cap;
wire    layer11_out_empty_n;
wire    layer4_out_full_n;
wire   [118:0] layer4_out_dout;
wire   [9:0] layer4_out_num_data_valid;
wire   [9:0] layer4_out_fifo_cap;
wire    layer4_out_empty_n;
wire    layer5_out_full_n;
wire   [111:0] layer5_out_dout;
wire   [9:0] layer5_out_num_data_valid;
wire   [9:0] layer5_out_fifo_cap;
wire    layer5_out_empty_n;
wire    layer6_out_full_n;
wire   [111:0] layer6_out_dout;
wire   [8:0] layer6_out_num_data_valid;
wire   [8:0] layer6_out_fifo_cap;
wire    layer6_out_empty_n;
wire    layer12_out_full_n;
wire   [671:0] layer12_out_dout;
wire   [5:0] layer12_out_num_data_valid;
wire   [5:0] layer12_out_fifo_cap;
wire    layer12_out_empty_n;
wire    layer13_out_full_n;
wire   [671:0] layer13_out_dout;
wire   [5:0] layer13_out_num_data_valid;
wire   [5:0] layer13_out_fifo_cap;
wire    layer13_out_empty_n;
wire   [0:0] start_for_repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_din;
wire    start_for_repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_full_n;
wire   [0:0] start_for_repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_dout;
wire    start_for_repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_din;
wire    start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_dout;
wire    start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_din;
wire    start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_dout;
wire    start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_din;
wire    start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_dout;
wire    start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_empty_n;
wire   [0:0] start_for_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_din;
wire    start_for_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_full_n;
wire   [0:0] start_for_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_dout;
wire    start_for_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_empty_n;
wire   [0:0] start_for_repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_din;
wire    start_for_repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_full_n;
wire   [0:0] start_for_repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_dout;
wire    start_for_repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_din;
wire    start_for_dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_full_n;
wire   [0:0] start_for_dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_dout;
wire    start_for_dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_empty_n;

cnn_core_transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_s transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_ap_start),
    .start_full_n(start_for_repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_full_n),
    .ap_done(transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_ap_done),
    .ap_continue(transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_ap_continue),
    .ap_idle(transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_ap_idle),
    .ap_ready(transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_ap_ready),
    .start_out(transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_start_out),
    .start_write(transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_start_write),
    .input_layer_TDATA(input_layer_TDATA),
    .input_layer_TVALID(input_layer_TVALID),
    .input_layer_TREADY(transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_input_layer_TREADY),
    .layer2_out_din(transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_layer2_out_din),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_full_n(layer2_out_full_n),
    .layer2_out_write(transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_layer2_out_write)
);

cnn_core_repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_s repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_full_n),
    .ap_done(repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_ap_done),
    .ap_continue(repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_ap_continue),
    .ap_idle(repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_ap_idle),
    .ap_ready(repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_ap_ready),
    .start_out(repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_start_out),
    .start_write(repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_start_write),
    .layer2_out_dout(layer2_out_dout),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_empty_n(layer2_out_empty_n),
    .layer2_out_read(repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_layer2_out_read),
    .layer11_out_din(repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_layer11_out_din),
    .layer11_out_num_data_valid(layer11_out_num_data_valid),
    .layer11_out_fifo_cap(layer11_out_fifo_cap),
    .layer11_out_full_n(layer11_out_full_n),
    .layer11_out_write(repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_layer11_out_write)
);

cnn_core_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_s conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_ap_ready),
    .layer11_out_dout(layer11_out_dout),
    .layer11_out_num_data_valid(layer11_out_num_data_valid),
    .layer11_out_fifo_cap(layer11_out_fifo_cap),
    .layer11_out_empty_n(layer11_out_empty_n),
    .layer11_out_read(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_layer11_out_read),
    .start_out(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_start_out),
    .start_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_start_write),
    .layer4_out_din(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_layer4_out_din),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_full_n(layer4_out_full_n),
    .layer4_out_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_layer4_out_write)
);

cnn_core_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_s relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_full_n),
    .ap_done(relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_ap_ready),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_layer4_out_read),
    .layer5_out_din(relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_layer5_out_din),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_full_n(layer5_out_full_n),
    .layer5_out_write(relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_layer5_out_write),
    .start_out(relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_start_out),
    .start_write(relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_start_write)
);

cnn_core_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_s pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_ap_start),
    .start_full_n(start_for_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_full_n),
    .ap_done(pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_ap_done),
    .ap_continue(pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_ap_continue),
    .ap_idle(pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_ap_idle),
    .ap_ready(pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_ap_ready),
    .layer6_out_din(pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_layer6_out_din),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer6_out_full_n(layer6_out_full_n),
    .layer6_out_write(pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_layer6_out_write),
    .layer5_out_dout(layer5_out_dout),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_empty_n(layer5_out_empty_n),
    .layer5_out_read(pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_layer5_out_read),
    .start_out(pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_start_out),
    .start_write(pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_start_write)
);

cnn_core_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_s repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_start),
    .start_full_n(start_for_repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_full_n),
    .ap_done(repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_done),
    .ap_continue(repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_continue),
    .ap_idle(repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_idle),
    .ap_ready(repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_ready),
    .layer6_out_dout(layer6_out_dout),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer6_out_empty_n(layer6_out_empty_n),
    .layer6_out_read(repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer6_out_read),
    .layer12_out_din(repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer12_out_din),
    .layer12_out_num_data_valid(layer12_out_num_data_valid),
    .layer12_out_fifo_cap(layer12_out_fifo_cap),
    .layer12_out_full_n(layer12_out_full_n),
    .layer12_out_write(repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer12_out_write),
    .start_out(repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_start_out),
    .start_write(repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_start_write)
);

cnn_core_repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_s repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_full_n),
    .ap_done(repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_done),
    .ap_continue(repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_continue),
    .ap_idle(repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_idle),
    .ap_ready(repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_ready),
    .layer12_out_dout(layer12_out_dout),
    .layer12_out_num_data_valid(layer12_out_num_data_valid),
    .layer12_out_fifo_cap(layer12_out_fifo_cap),
    .layer12_out_empty_n(layer12_out_empty_n),
    .layer12_out_read(repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer12_out_read),
    .layer13_out_din(repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer13_out_din),
    .layer13_out_num_data_valid(layer13_out_num_data_valid),
    .layer13_out_fifo_cap(layer13_out_fifo_cap),
    .layer13_out_full_n(layer13_out_full_n),
    .layer13_out_write(repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer13_out_write),
    .start_out(repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_start_out),
    .start_write(repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_start_write)
);

cnn_core_dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_s dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_ap_start),
    .ap_done(dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_ap_done),
    .ap_continue(dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_ap_continue),
    .ap_idle(dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_ap_idle),
    .ap_ready(dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_ap_ready),
    .layer13_out_dout(layer13_out_dout),
    .layer13_out_num_data_valid(layer13_out_num_data_valid),
    .layer13_out_fifo_cap(layer13_out_fifo_cap),
    .layer13_out_empty_n(layer13_out_empty_n),
    .layer13_out_read(dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_layer13_out_read),
    .layer10_out_TDATA(dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_layer10_out_TDATA),
    .layer10_out_TVALID(dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_layer10_out_TVALID),
    .layer10_out_TREADY(layer10_out_TREADY)
);

cnn_core_fifo_w3072_d4_A layer2_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_layer2_out_din),
    .if_full_n(layer2_out_full_n),
    .if_write(transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_layer2_out_write),
    .if_dout(layer2_out_dout),
    .if_num_data_valid(layer2_out_num_data_valid),
    .if_fifo_cap(layer2_out_fifo_cap),
    .if_empty_n(layer2_out_empty_n),
    .if_read(repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_layer2_out_read)
);

cnn_core_fifo_w12_d1024_A layer11_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_layer11_out_din),
    .if_full_n(layer11_out_full_n),
    .if_write(repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_layer11_out_write),
    .if_dout(layer11_out_dout),
    .if_num_data_valid(layer11_out_num_data_valid),
    .if_fifo_cap(layer11_out_fifo_cap),
    .if_empty_n(layer11_out_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_layer11_out_read)
);

cnn_core_fifo_w119_d336_A layer4_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_layer4_out_din),
    .if_full_n(layer4_out_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_layer4_out_write),
    .if_dout(layer4_out_dout),
    .if_num_data_valid(layer4_out_num_data_valid),
    .if_fifo_cap(layer4_out_fifo_cap),
    .if_empty_n(layer4_out_empty_n),
    .if_read(relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_layer4_out_read)
);

cnn_core_fifo_w112_d336_A layer5_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_layer5_out_din),
    .if_full_n(layer5_out_full_n),
    .if_write(relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_layer5_out_write),
    .if_dout(layer5_out_dout),
    .if_num_data_valid(layer5_out_num_data_valid),
    .if_fifo_cap(layer5_out_fifo_cap),
    .if_empty_n(layer5_out_empty_n),
    .if_read(pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_layer5_out_read)
);

cnn_core_fifo_w112_d168_A layer6_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_layer6_out_din),
    .if_full_n(layer6_out_full_n),
    .if_write(pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_layer6_out_write),
    .if_dout(layer6_out_dout),
    .if_num_data_valid(layer6_out_num_data_valid),
    .if_fifo_cap(layer6_out_fifo_cap),
    .if_empty_n(layer6_out_empty_n),
    .if_read(repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer6_out_read)
);

cnn_core_fifo_w672_d28_A layer12_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer12_out_din),
    .if_full_n(layer12_out_full_n),
    .if_write(repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer12_out_write),
    .if_dout(layer12_out_dout),
    .if_num_data_valid(layer12_out_num_data_valid),
    .if_fifo_cap(layer12_out_fifo_cap),
    .if_empty_n(layer12_out_empty_n),
    .if_read(repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer12_out_read)
);

cnn_core_fifo_w672_d28_A layer13_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer13_out_din),
    .if_full_n(layer13_out_full_n),
    .if_write(repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_layer13_out_write),
    .if_dout(layer13_out_dout),
    .if_num_data_valid(layer13_out_num_data_valid),
    .if_fifo_cap(layer13_out_fifo_cap),
    .if_empty_n(layer13_out_empty_n),
    .if_read(dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_layer13_out_read)
);

cnn_core_start_for_repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024cud start_for_repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024cud_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_din),
    .if_full_n(start_for_repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_full_n),
    .if_write(transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_start_write),
    .if_dout(start_for_repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_dout),
    .if_empty_n(start_for_repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_empty_n),
    .if_read(repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_ap_ready)
);

cnn_core_start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0 start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_full_n),
    .if_write(repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_empty_n),
    .if_read(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_ap_ready)
);

cnn_core_start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0 start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_empty_n),
    .if_read(relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_ap_ready)
);

cnn_core_start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6dEe start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6dEe_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_din),
    .if_full_n(start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_full_n),
    .if_write(relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_start_write),
    .if_dout(start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_empty_n),
    .if_read(pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_ap_ready)
);

cnn_core_start_for_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0 start_for_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_din),
    .if_full_n(start_for_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_full_n),
    .if_write(pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_start_write),
    .if_dout(start_for_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_dout),
    .if_empty_n(start_for_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_empty_n),
    .if_read(repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_ready)
);

cnn_core_start_for_repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176eOg start_for_repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176eOg_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_din),
    .if_full_n(start_for_repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_full_n),
    .if_write(repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_start_write),
    .if_dout(start_for_repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_dout),
    .if_empty_n(start_for_repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_empty_n),
    .if_read(repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_ready)
);

cnn_core_start_for_dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0 start_for_dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_din),
    .if_full_n(start_for_dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_full_n),
    .if_write(repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_start_write),
    .if_dout(start_for_dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_dout),
    .if_empty_n(start_for_dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_empty_n),
    .if_read(dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_ap_ready)
);

assign ap_done = dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_ap_done;

assign ap_idle = (transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_ap_idle & repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_idle & repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_idle & repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_ap_idle & relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_ap_idle & pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_ap_idle & dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_ap_idle & conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_ap_idle);

assign ap_ready = transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_ap_start = start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_empty_n;

assign dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_ap_continue = 1'b1;

assign dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_ap_start = start_for_dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_empty_n;

assign input_layer_TREADY = transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_input_layer_TREADY;

assign layer10_out_TDATA = dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_layer10_out_TDATA;

assign layer10_out_TVALID = dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_layer10_out_TVALID;

assign pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_ap_continue = 1'b1;

assign pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_ap_start = start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_empty_n;

assign relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_ap_start = start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_empty_n;

assign repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_ap_continue = 1'b1;

assign repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_ap_start = start_for_repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_empty_n;

assign repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_continue = 1'b1;

assign repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_start = start_for_repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_empty_n;

assign repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_continue = 1'b1;

assign repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_ap_start = start_for_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_empty_n;

assign start_for_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_17_9_5_3_0_7u_config4_U0_din = 1'b1;

assign start_for_dense_array_ap_fixed_42u_array_ap_fixed_17_9_5_3_0_1u_config10_U0_din = 1'b1;

assign start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config6_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config5_U0_din = 1'b1;

assign start_for_repack_stream_array_ap_fixed_256u_array_ap_fixed_12_6_5_3_0_1u_1024_U0_din = 1'b1;

assign start_for_repack_stream_array_ap_fixed_42u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_din = 1'b1;

assign start_for_repack_stream_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_42u_1176_U0_din = 1'b1;

assign transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_ap_continue = 1'b1;

assign transpose_array_ap_fixed_4u_array_ap_fixed_12_6_5_3_0_256u_config2_U0_ap_start = ap_start;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "cnn_core_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "cnn_core_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //cnn_core

