// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_core_compute_output_buffer_1d_array_array_ap_fixed_17_9_5_3_0_7u_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        in_elem_0_0_0_0_0_val,
        layer4_out_din,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer4_out_full_n,
        layer4_out_write,
        layer4_out_blk_n
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [11:0] in_elem_0_0_0_0_0_val;
output  [118:0] layer4_out_din;
input  [9:0] layer4_out_num_data_valid;
input  [9:0] layer4_out_fifo_cap;
input   layer4_out_full_n;
output   layer4_out_write;
output   layer4_out_blk_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer4_out_write;
reg layer4_out_blk_n;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
reg    ap_block_pp0_stage2_subdone;
reg   [11:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3;
reg   [11:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2;
reg   [11:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1;
reg   [11:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data;
reg   [11:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4;
reg   [31:0] sX_1;
reg   [31:0] pX_1;
wire    ap_block_pp0_stage0;
reg   [0:0] and_ln350_reg_256;
wire   [0:0] and_ln350_fu_166_p2;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [31:0] add_ln376_fu_198_p2;
reg   [16:0] res_out_reg_268;
wire    ap_block_pp0_stage2_11001;
reg   [16:0] res_out_1_reg_273;
reg   [16:0] res_out_2_reg_278;
reg   [16:0] res_out_3_reg_283;
reg   [16:0] res_out_4_reg_288;
reg   [16:0] res_out_5_reg_293;
reg   [16:0] res_out_6_reg_298;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [16:0] grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_0;
wire   [16:0] grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_1;
wire   [16:0] grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_2;
wire   [16:0] grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_3;
wire   [16:0] grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_4;
wire   [16:0] grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_5;
wire   [16:0] grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_6;
reg    grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_ce;
wire    ap_block_pp0_stage1_11001_ignoreCallOp23;
wire    ap_block_pp0_stage2_11001_ignoreCallOp33;
reg   [31:0] ap_phi_reg_pp0_iter0_storemerge_reg_65;
wire   [0:0] icmp_ln369_fu_178_p2;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage2;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] add_ln369_fu_172_p2;
reg    ap_block_pp0_stage0_01001;
wire   [29:0] tmp_1_fu_150_p4;
wire   [0:0] icmp_ln350_fu_140_p2;
wire   [0:0] icmp_ln350_1_fu_160_p2;
wire   [31:0] select_ln376_fu_190_p3;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
reg    ap_condition_151;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3 = 12'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2 = 12'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1 = 12'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data = 12'd0;
#0 void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4 = 12'd0;
#0 sX_1 = 32'd0;
#0 pX_1 = 32'd0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

cnn_core_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1),
    .void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data),
    .ap_return_0(grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_2),
    .ap_return_3(grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_3),
    .ap_return_4(grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_4),
    .ap_return_5(grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_5),
    .ap_return_6(grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_6),
    .ap_ce(grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_151)) begin
        if ((icmp_ln369_fu_178_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_storemerge_reg_65 <= 32'd0;
        end else if ((icmp_ln369_fu_178_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_storemerge_reg_65 <= add_ln376_fu_198_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_151)) begin
        if ((icmp_ln369_fu_178_p2 == 1'd1)) begin
            pX_1 <= 32'd0;
        end else if ((icmp_ln369_fu_178_p2 == 1'd0)) begin
            pX_1 <= add_ln369_fu_172_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        and_ln350_reg_256 <= and_ln350_fu_166_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        res_out_1_reg_273 <= grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_1;
        res_out_2_reg_278 <= grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_2;
        res_out_3_reg_283 <= grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_3;
        res_out_4_reg_288 <= grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_4;
        res_out_5_reg_293 <= grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_5;
        res_out_6_reg_298 <= grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_6;
        res_out_reg_268 <= grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sX_1 <= ap_phi_reg_pp0_iter0_storemerge_reg_65;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data <= in_elem_0_0_0_0_0_val;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4 <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp33) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp23) & (1'b1 == ap_CS_fsm_pp0_stage1))))) begin
        grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_ap_fixed_12_6_5_3_0_ap_fixed_17_9_5_3_0_config4_mult_s_fu_76_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln350_reg_256) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer4_out_blk_n = layer4_out_full_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln350_reg_256) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer4_out_write = 1'b1;
    end else begin
        layer4_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln369_fu_172_p2 = (pX_1 + 32'd1);

assign add_ln376_fu_198_p2 = (sX_1 + select_ln376_fu_190_p3);

assign and_ln350_fu_166_p2 = (icmp_ln350_fu_140_p2 & icmp_ln350_1_fu_160_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_ignoreCallOp23 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001_ignoreCallOp33 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (1'b0 == ap_ce);
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = ((1'd1 == and_ln350_reg_256) & (layer4_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_151 = ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign icmp_ln350_1_fu_160_p2 = (($signed(tmp_1_fu_150_p4) > $signed(30'd0)) ? 1'b1 : 1'b0);

assign icmp_ln350_fu_140_p2 = ((sX_1 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln369_fu_178_p2 = ((add_ln369_fu_172_p2 == 32'd256) ? 1'b1 : 1'b0);

assign layer4_out_din = {{{{{{{res_out_6_reg_298}, {res_out_5_reg_293}}, {res_out_4_reg_288}}, {res_out_3_reg_283}}, {res_out_2_reg_278}}, {res_out_1_reg_273}}, {res_out_reg_268}};

assign select_ln376_fu_190_p3 = ((icmp_ln350_fu_140_p2[0:0] == 1'b1) ? 32'd4294967294 : 32'd1);

assign tmp_1_fu_150_p4 = {{pX_1[31:2]}};

endmodule //cnn_core_compute_output_buffer_1d_array_array_ap_fixed_17_9_5_3_0_7u_config4_s
